#!/bin/bash -e

cat <<EOF
This is the enroute-jpm4j-app S2I image:
To use it, install S2I: https://github.com/openshift/source-to-image

Example building osgi.enroute.examples.rest.application:

s2i build osgi.enroute.examples.rest.application kameshsampath/enroute-jpm4j-app enroute-rest-app

You can then run the resulting image via:
docker run -d -p 8080:8080 enroute-rest-app
and see the test via http://<docker ip>:8080
EOF