#!/bin/bash -e

if [[ "$1" == "-h" ]]; then
  # If the 'enroute-app' assemble script is executed with '-h' flag,
  # print the usage.
  exec /opt/enroute/s2i/usage
fi

export JAVA_HOME=/etc/alternatives/java_sdk

cd /tmp/src 

chmod +x gradlew

_export_app_task="export.${ENROUTE_APP_BND_RUN}"

echo "--->  Building executable jar for ${ENROUTE_APP} ...."

## FIME me enable test
exec ./gradlew -x test build ${_export_app_task}

#
# Last step application using JPM4J
#
if [ -f "/tmp/src/${ENROUTE_APP}/generated/distributions/executable/${ENROUTE_APP_BND_RUN}.jar" ]; then
  echo "Application successfully generated "
  cp -av "/tmp/src/${ENROUTE_APP}/generated/distributions/executable/${ENROUTE_APP_BND_RUN}.jar" ${HOME}
  chmod +x "${HOME}/${ENROUTE_APP_BND_RUN}.jar"
  jpm install --name $JPM_COMMAND --force "${HOME}/${ENROUTE_APP_BND_RUN}.jar"
fi
